@startuml
skinparam shadowing false
title UC21 - Lưu CV ứng viên
|Nhà tuyển dụng|
start
:Mở CV ứng viên;
:Nhận Lưu CV;
|Hệ thống|
:Kiểm tra đăng nhập;
if (Đã đăng nhập?) then (Có)
  :Lưu CV ứng viên vào danh sách quan tâm;
  |Nhà tuyển dụng|
  :Nhận thông báo đã lưu;
  stop
else (Không)
  |Nhà tuyển dụng|
  :Đăng nhập để tiếp tục;
  stop
endif
@enduml
