sequenceDiagram
    actor Guest as Khách vãng lai
    participant UI as Hệ thống(UI)
    participant Job as Dịch vụ việc làm
    participant DB as CSDL
    Guest->>UI: Nhập từ khóa, địa điểm, mức lương
    UI->>Job: Gửi bộ lọc tìm kiếm
    Job->>DB: Truy vấn danh sách việc làm
    DB-->>Job: Trả kết quả phù hợp
    Job-->>UI: Danh sách việc làm đã lọc
    UI-->>Guest: Hiển thị kết quả tìm kiếm
