sequenceDiagram
    actor Guest as Khách vãng lai
    participant UI as Hệ thống(UI)
    participant Job as Dịch vụ việc làm
    participant Company as Dịch vụ công ty
    participant DB as CSDL
    Guest->>UI: Chọn một tin tuyển dụng
    UI->>Job: Lấy chi tiết tin
    Job->>DB: Truy vấn thông tin tin tuyển dụng
    Job->>Company: Lấy thông tin công ty liên quan
    Company->>DB: Truy vấn hồ sơ công ty
    DB-->>Company: Hồ sơ công ty
    DB-->>Job: Chi tiết tin
    Job-->>UI: Gồm chi tiết tin và thông tin công ty
    UI-->>Guest: Hiển thị trang chi tiết
