@startuml
skinparam shadowing false
left to right direction
title UC04 - Tìm kiếm việc làm
actor "Khách vãng lai" as ACTOR_1
usecase "Tìm kiếm việc làm" as UC_MAIN
ACTOR_1 --> UC_MAIN
usecase "Tìm kiếm việc làm theo từ khóa" as UC_EXT_1
UC_EXT_1 ..> UC_MAIN : <<extend>>
usecase "Tìm kiếm việc làm theo địa điểm" as UC_EXT_2
UC_EXT_2 ..> UC_MAIN : <<extend>>
usecase "Tìm kiếm việc làm theo mức lương" as UC_EXT_3
UC_EXT_3 ..> UC_MAIN : <<extend>>
@enduml
